spring:
  application:
    name: movie-auth-service
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      enabled: true
  jpa:
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8889/eureka/