server:
  port: 9091

spring:
  datasource:
    url: jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
    username: ${PROD_DB_USER}
    password: ${PROD_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update


springdoc:
  api-docs:
    path=/api-docs:
      enabled: true